### ISSUE TITLE
support root node is array

### ISSUE THREAD

**Issue by rustbomber** [jjfiv/access-json#1]
if JSON  root node is array， report error：MissingFiled

**Comment by jjfiv** [comment]
Hi @akaylh,

Do you mean a literal rust array? It's been a while since I've been in the code, but we definitely support Vec as a 'root' of the tree to access. Maybe that gives you a workaround.

https://github.com/jjfiv/access-json/blob/e5367c606bd24ef142f7f4bcc0ae226eb730f239/src/lib.rs#L343-L362

Could you share a small example -- or some more details -- of what's not working?

**Comment by rustbomber** [comment]
I mean  json array, like this:

```json
[
{},
{}
]
```

**Comment by jjfiv** [comment]
... Can you share the query you're trying to run?
Ideally, the ``#[derive(Serialize)]`` struct as well? 

After reviewing the tests and 2023c51 I'm pretty sure the data structure you're querying is not the cause here.

``MissingField`` comes up when you have a malformed query, e.g., when a ``'.'`` is not followed by a field name... but another '[' or '.' or the end of the string.

**Comment by rustbomber** [comment]
my json is array , have two object。

```json
[
    {
        "header": {
            "subcenter": 0,
            "refTime": "2021-04-22T23:00:00",
            "dx": 1,
            "dy": 1
        },
        "data": [
            0.2725049,
            0.20250489
        ]
    },
    {
        "header": {
            "subcenter": 0,
            "refTime": "2021-04-23T23:00:00",
            "dx": 1,
            "dy": 1
        },
        "data": [
            0.2725049,
            0.20250489
        ]
    }
]
```

now I want to get `refTime` filed, so I write Jsonpath is : `.[0].header.refTime`，`.[1].header.refTime`，  report MissingField error。

**Comment by jjfiv** [comment]
Your query needs to drop the leading ``.`` in this case. I'm not that familiar with JSONPath, but this crate's syntax is much simpler; it's not currently a goal to support JSONPath.

The query you want is:
``[0].header.refTime``

We only support a sequence of operators, which are either ``[INDEX]`` or ``.FIELD``.

You're getting a ``MissingField`` because the ``.[0]`` part is not understood. It thinks you're missing a field name between the ``.`` and the ``[``.

**Comment by rustbomber** [comment]
@jjfiv thank you very much. I use `[0].header.refTime`, is work fine.
